name: EternalWolf
main: net.robinjam.bukkit.eternalwolf.EternalWolf
version: ${project.version}
commands:
  call-wolves:
    description: Call all your wolves to your current location
    usage: /<command>
